### ISSUE TITLE
Incorrect punycodes for emoji?

### ISSUE THREAD

**Issue by warpling** [Wevah/Punycode-Cocoa#10]
I'm trying to encode emoji like 😀 and ⬛️  to punycode. 

I noticed that Safari (and [this converter](https://www.punycoder.com/)) encode some emoji differently than the library. Is this a bug causing something extra to get appended or is it just a disparity in encodings?

Emoji | Safari | Punycode-Cocoa
--- | ------------ | -------------
😀 | `xn--e28h` | `xn--e28h`
⬛️ | `xn--w5i` | `xn--w5ix313e` 
▪️ | `xn--30h` | `xn--30h0620f`

**Comment by Wevah** [comment]
I think I know what it is: It's actually encoding 2 characters, the second of which is an invisible character that says either "use the emoji version of this character" or "use the non-emoji version of this character".

Regardless, this should be fixed.

**Comment by Wevah** [comment]
This should be fixed in the latest push (1.2). Reopen and let me know if it's not!

**Comment by warpling** [comment]
Sorry I lost track of this @Wevah! Thanks for the quick fix; I'm impressed by your speed!
This is already live (not the fix quite yet) in my game [Blackbox](www.blackboxpuzzles.com) btw! The challenge that uses it is *pretttty* hard to find though. (clue on the website 😉)

**Comment by warpling** [comment]
Looks like podspec still needs a bump!

**Comment by Wevah** [comment]
Good call!

**Comment by Wevah** [comment]
Addendum: I've fixed the variation selector range and added the rest of the ignored characters from the stringprep RFC (RFC 3454).
