### ISSUE TITLE
Using with Swift 3.0

### ISSUE THREAD

**Issue by mobinzk** [Wevah/Punycode-Cocoa#11]
Any suggestion how I can use this with Swift 3.0 via pod?

**Comment by mobinzk** [comment]
I've found the answer.

In pod file added:
```
use_frameworks!
target 'TARGET_NAME' do
pod 'Punycode-Cocoa', '~>1.0'
end
```

Then in code used like this:
```
import Punycode_Cocoa

"String".idnaDecoded
```

**Comment by Wevah** [comment]
I'm glad you got it resolved! (I don't do very much Swift work yet.)
