### ISSUE TITLE
URLParts -> NSURLComponents

### ISSUE THREAD

**Issue by rudyrichter** [Wevah/Punycode-Cocoa#12]
I think you'll have slightly less janky code if you use NSURLComponents to digest a particular url into its components rather than scanning through strings for separator characters.

**Comment by Wevah** [comment]
IIRC there was a reason I didn't, but I can't remember what it was now.

**Comment by Wevah** [comment]
Oh, right, it's because NSURLComponents chokes on non-ASCII like NSURL does. :(

**Comment by Wevah** [comment]
Closing for afformentioned reason; may revisit in the future.
