### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by KrzysztofLoza** [Wevah/Punycode-Cocoa#9]
Methods CFURLCreateStringByAddingPercentEscapes and stringByReplacingPercentEscapesUsingEncoding are deprecated in iOS 9. Is it possible to update the code so that it won't generate warnings?

**Comment by Wevah** [comment]
I've updated this; it now requires 10.9 (or the equivalent iOS version) to build.

**Comment by Wevah** [comment]
I've updated this; it now requires 10.9 (or the equivalent iOS version) to build.

**Comment by Wevah** [comment]
(Should be fixed in all the spots now.)
